{% set name = "pychemia" %}
{% set version = "0.21.9.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 610a07d97a7b3bcc94d05e83bf85c99a65a0d25b0e8ccad59f3a619ef6282928

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - matplotlib-base >=3.0
    - numpy >=1.17
    - psutil >=5.6
    - pymongo >=3.9
    - python
    - scipy >=1.3
    - spglib >=1.9

test:
  imports:
    - pychemia
    - pychemia.analysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://materialsdiscovery.github.io/PyChemia
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python Framework for Materials Discovery and Design

  description: |
    PyChemia is an open-source Python Library for materials structural 
    search. The purpose of the initiative is to create a method agnostic 
    framework for materials discovery and design using a variety of 
    methods from Minima Hoping to Soft-computing based methods. PyChemia 
    is also a library for data-mining, using several methods to discover 
    interesting candidates among the materials already processed.
  doc_url: https://materialsdiscovery.github.io/PyChemia
  dev_url: https://github.com/materialsdiscovery/PyChemia


extra:
  recipe-maintainers:
    - jan-janssen
    - guilleaf
